/**
 * Clerk Backend API
 * The Clerk REST Backend API, meant to be accessed by backend servers. Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.davisuga.clerk4s.api

import com.davisuga.clerk4s.core.JsonSupport._
import sttp.client3._
import sttp.model.Method

object JWKSApi {

def apply(baseUrl: String = "https://api.clerk.com/v1") = new JWKSApi(baseUrl)
}

class JWKSApi(baseUrl: String) {

  /**
   * Retrieve the JSON Web Key Set of the instance
   * 
   * Expected answers:
   *   code 200 :  (The JSON Web Key Set)
   * 
   * Available security schemes:
   *   bearerAuth (http)
   */
  def getJWKS(bearerToken: String)(
): Request[Either[ResponseException[String, Exception], Unit], Any] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/jwks")
      .contentType("application/json")
      .auth.bearer(bearerToken)
      .response(asJson[Unit])

}
