/**
 * Clerk Backend API
 * The Clerk REST Backend API, meant to be accessed by backend servers. Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.davisuga.clerk4s.model


case class AddDomainRequest(
  /* The new domain name. Can contain the port for development instances. */
  name: String,
  /* Marks the new domain as satellite. Only `true` is accepted at the moment. */
  isSatellite: Boolean,
  /* The full URL of the proxy which will forward requests to the Clerk Frontend API for this domain. Applicable only to production instances. */
  proxyUrl: Option[String] = None
)

