/**
 * Clerk Backend API
 * The Clerk REST Backend API, meant to be accessed by backend servers. Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.davisuga.clerk4s.model


case class Client(
  /* String representing the object's type. Objects of the same type share the same value.  */
  `object`: ClientEnums.`Object`,
  /* String representing the identifier of the session.  */
  id: String,
  sessionIds: Seq[String],
  sessions: Seq[Session],
  signInId: String,
  signUpId: String,
  /* Last active session_id.  */
  lastActiveSessionId: String,
  /* Unix timestamp of last update.  */
  updatedAt: Long,
  /* Unix timestamp of creation.  */
  createdAt: Long
)

object ClientEnums {

  type `Object` = `Object`.Value
  object `Object` extends Enumeration {
    val Client = Value("client")
  }

}
