/**
 * Clerk Backend API
 * The Clerk REST Backend API, meant to be accessed by backend servers. Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.davisuga.clerk4s.model


case class CreateSAMLConnectionRequest(
  /* The name to use as a label for this SAML Connection */
  name: String,
  /* The domain of your organization. Sign in flows using an email with this domain, will use this SAML Connection. */
  domain: String,
  /* The Entity ID as provided by the IdP */
  idpEntityId: Option[String] = None,
  /* The Single-Sign On URL as provided by the IdP */
  idpSsoUrl: Option[String] = None,
  /* The X.509 certificate as provided by the IdP */
  idpCertificate: Option[String] = None
)

