/**
 * Clerk Backend API
 * The Clerk REST Backend API, meant to be accessed by backend servers. Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.davisuga.clerk4s.model


case class CreateSignInTokenRequest(
  /* The ID of the user that can use the newly created sign in token */
  userId: Option[String] = None,
  /* Optional parameter to specify the life duration of the sign in token in seconds. By default, the duration is 30 days. */
  expiresInSeconds: Option[Int] = None
)

