/**
 * Clerk Backend API
 * The Clerk REST Backend API, meant to be accessed by backend servers. Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.davisuga.clerk4s.model


case class CreateJWTTemplateRequest(
  /* JWT template name */
  name: Option[String] = None,
  /* JWT template claims in JSON format */
  claims: Option[Any] = None,
  /* JWT token lifetime */
  lifetime: Option[Double] = None,
  /* JWT token allowed clock skew */
  allowedClockSkew: Option[Double] = None,
  /* Whether a custom signing key/algorithm is also provided for this template */
  customSigningKey: Option[Boolean] = None,
  /* The custom signing algorithm to use when minting JWTs */
  signingAlgorithm: Option[String] = None,
  /* The custom signing private key to use when minting JWTs */
  signingKey: Option[String] = None
)

