/**
 * Clerk Backend API
 * The Clerk REST Backend API, meant to be accessed by backend servers. Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.davisuga.clerk4s.model


case class CreateOrganizationRequest(
  /* The name of the new organization */
  name: String,
  /* The ID of the User who will become the administrator for the new organization */
  createdBy: String,
  /* Metadata saved on the organization, accessible only from the Backend API */
  privateMetadata: Option[Any] = None,
  /* Metadata saved on the organization, read-only from the Frontend API and fully accessible (read/write) from the Backend API */
  publicMetadata: Option[Any] = None,
  /* A slug for the new organization. Can contain only lowercase alphanumeric characters and the dash \"-\". Must be unique for the instance. */
  slug: Option[String] = None,
  /* The maximum number of memberships allowed for this organization */
  maxAllowedMemberships: Option[Int] = None
)

