/**
 * Clerk Backend API
 * The Clerk REST Backend API, meant to be accessed by backend servers. Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.davisuga.clerk4s.model


case class CreateAllowlistIdentifierRequest(
  /* The identifier to be added in the allow-list. This can be an email address, a phone number or a web3 wallet. */
  identifier: String,
  /* This flag denotes whether the given identifier will receive an invitation to join the application. Note that this only works for email address and phone number identifiers. */
)

