/**
 * Clerk Backend API
 * The Clerk REST Backend API, meant to be accessed by backend servers. Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.davisuga.clerk4s.model


case class CreateSessionTokenFromTemplate200Response(
  `object`: Option[CreateSessionTokenFromTemplate200ResponseEnums.`Object`] = None,
  jwt: Option[String] = None
)

object CreateSessionTokenFromTemplate200ResponseEnums {

  type `Object` = `Object`.Value
  object `Object` extends Enumeration {
    val Token = Value("token")
  }

}
