/**
 * Clerk Backend API
 * The Clerk REST Backend API, meant to be accessed by backend servers. Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.davisuga.clerk4s.model


case class CreatePhoneNumberRequest(
  /* The ID representing the user */
  userId: Option[String] = None,
  /* The new phone number. Must adhere to the E.164 standard for phone number format. */
  phoneNumber: Option[String] = None,
  /* When created, the phone number will be marked as verified. */
  verified: Option[Boolean] = None,
  /* Create this phone number as the primary phone number for the user. Default: false, unless it is the first phone number. */
  primary: Option[Boolean] = None
)

