/**
 * Clerk Backend API
 * The Clerk REST Backend API, meant to be accessed by backend servers. Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.davisuga.clerk4s.model


case class CreateActorTokenRequest(
  /* The ID of the user that can use the newly created sign in token. */
  userId: String,
  /* The actor payload. It needs to include a sub property which should contain the ID of the actor. This whole payload will be also included in the JWT session token. */
  actor: Any,
  /* Optional parameter to specify the life duration of the actor token in seconds. By default, the duration is 1 hour. */
  expiresInSeconds: Option[Int] = None,
  /* The maximum duration that the session which will be created by the generated actor token should last. By default, the duration of a session created via an actor token, lasts 30 minutes. */
  sessionMaxDurationInSeconds: Option[Int] = None
)

