/**
 * Clerk Backend API
 * The Clerk REST Backend API, meant to be accessed by backend servers. Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.davisuga.clerk4s.model


case class GetOAuthAccessToken200ResponseInner(
  `object`: Option[String] = None,
  /* The access token */
  token: Option[String] = None,
  /* The ID of the provider */
  provider: Option[String] = None,
  publicMetadata: Option[Any] = None,
  label: Option[String] = None,
  /* The list of scopes that the token is valid for. Only present for OAuth 2.0 tokens. */
  scopes: Option[Seq[String]] = None,
  /* The token secret. Only present for OAuth 1.0 tokens. */
  tokenSecret: Option[String] = None
)

