/**
 * Clerk Backend API
 * The Clerk REST Backend API, meant to be accessed by backend servers. Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.davisuga.clerk4s.model


case class IdentificationLink(
  `type`: IdentificationLinkEnums.`Type`,
  id: String
)

object IdentificationLinkEnums {

  type `Type` = `Type`.Value
  object `Type` extends Enumeration {
    val OauthGoogle = Value("oauth_google")
    val OauthMock = Value("oauth_mock")
    val Saml = Value("saml")
  }

}
