/**
 * Clerk Backend API
 * The Clerk REST Backend API, meant to be accessed by backend servers. Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.davisuga.clerk4s.model


case class JWTTemplate(
  `object`: JWTTemplateEnums.`Object`,
  id: String,
  name: String,
  claims: Any,
  lifetime: Int,
  allowedClockSkew: Int,
  customSigningKey: Option[Boolean] = None,
  signingAlgorithm: Option[String] = None,
  /* Unix timestamp of creation.  */
  createdAt: Long,
  /* Unix timestamp of last update.  */
  updatedAt: Long
)

object JWTTemplateEnums {

  type `Object` = `Object`.Value
  object `Object` extends Enumeration {
    val JwtTemplate = Value("jwt_template")
  }

}
