/**
 * Clerk Backend API
 * The Clerk REST Backend API, meant to be accessed by backend servers. Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.davisuga.clerk4s.model


case class OrganizationWithLogo(
  `object`: OrganizationWithLogoEnums.`Object`,
  id: String,
  name: String,
  slug: String,
  membersCount: Option[Int] = None,
  maxAllowedMemberships: Int,
  adminDeleteEnabled: Option[Boolean] = None,
  publicMetadata: Any,
  privateMetadata: Any,
  createdBy: Option[String] = None,
  /* Unix timestamp of creation.  */
  createdAt: Long,
  /* Unix timestamp of last update.  */
  updatedAt: Long,
  logoUrl: String,
  imageUrl: Option[String] = None
)

object OrganizationWithLogoEnums {

  type `Object` = `Object`.Value
  object `Object` extends Enumeration {
    val Organization = Value("organization")
  }

}
