/**
 * Clerk Backend API
 * The Clerk REST Backend API, meant to be accessed by backend servers. Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.davisuga.clerk4s.model


  /**
   * An organization invitation
   */
case class OrganizationInvitation(
  id: Option[String] = None,
  /* String representing the object's type. Objects of the same type share the same value.  */
  `object`: Option[OrganizationInvitationEnums.`Object`] = None,
  emailAddress: Option[String] = None,
  role: Option[OrganizationInvitationEnums.Role] = None,
  organizationId: Option[String] = None,
  status: Option[String] = None,
  publicMetadata: Option[Any] = None,
  privateMetadata: Option[Any] = None,
  /* Unix timestamp of creation. */
  createdAt: Option[Long] = None,
  /* Unix timestamp of last update. */
  updatedAt: Option[Long] = None
)

object OrganizationInvitationEnums {

  type `Object` = `Object`.Value
  type Role = Role.Value
  object `Object` extends Enumeration {
    val OrganizationInvitation = Value("organization_invitation")
  }

  object Role extends Enumeration {
    val Admin = Value("admin")
    val BasicMember = Value("basic_member")
  }

}
