/**
 * Clerk Backend API
 * The Clerk REST Backend API, meant to be accessed by backend servers. Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.davisuga.clerk4s.model


case class OrganizationSettings(
  /* String representing the object's type. Objects of the same type share the same value. */
  `object`: OrganizationSettingsEnums.`Object`,
  enabled: Boolean,
  maxAllowedMemberships: Int,
  /* The default for whether an admin can delete an organization with the Frontend API. */
  adminDeleteEnabled: Option[Boolean] = None
)

object OrganizationSettingsEnums {

  type `Object` = `Object`.Value
  object `Object` extends Enumeration {
    val OrganizationSettings = Value("organization_settings")
  }

}
