/**
 * Clerk Backend API
 * The Clerk REST Backend API, meant to be accessed by backend servers. Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.davisuga.clerk4s.model


case class OTP(
  status: OTPEnums.Status,
  strategy: OTPEnums.Strategy,
  attempts: Int,
  expireAt: Int
)

object OTPEnums {

  type Status = Status.Value
  type Strategy = Strategy.Value
  object Status extends Enumeration {
    val Unverified = Value("unverified")
    val Verified = Value("verified")
    val Failed = Value("failed")
    val Expired = Value("expired")
  }

  object Strategy extends Enumeration {
    val PhoneCode = Value("phone_code")
    val EmailCode = Value("email_code")
  }

}
