/**
 * Clerk Backend API
 * The Clerk REST Backend API, meant to be accessed by backend servers. Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.davisuga.clerk4s.model


case class PhoneNumber(
  id: Option[String] = None,
  /* String representing the object's type. Objects of the same type share the same value.  */
  `object`: PhoneNumberEnums.`Object`,
  phoneNumber: String,
  reservedForSecondFactor: Option[Boolean] = None,
  defaultSecondFactor: Option[Boolean] = None,
  reserved: Boolean,
  verification: EmailAddressVerification,
  linkedTo: Seq[IdentificationLink],
  backupCodes: Option[Seq[String]] = None
)

object PhoneNumberEnums {

  type `Object` = `Object`.Value
  object `Object` extends Enumeration {
    val PhoneNumber = Value("phone_number")
  }

}
