/**
 * Clerk Backend API
 * The Clerk REST Backend API, meant to be accessed by backend servers. Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.davisuga.clerk4s.model


case class RedirectURL(
  `object`: RedirectURLEnums.`Object`,
  id: String,
  url: String,
  /* Unix timestamp of creation.  */
  createdAt: Long,
  /* Unix timestamp of last update.  */
  updatedAt: Long
)

object RedirectURLEnums {

  type `Object` = `Object`.Value
  object `Object` extends Enumeration {
    val RedirectUrl = Value("redirect_url")
  }

}
