/**
 * Clerk Backend API
 * The Clerk REST Backend API, meant to be accessed by backend servers. Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.davisuga.clerk4s.model


case class SAML(
  status: SAMLEnums.Status,
  strategy: SAMLEnums.Strategy,
  externalVerificationRedirectUrl: String,
  error: Option[SAMLError] = None,
  expireAt: Int,
  attempts: Option[Int] = None
)

object SAMLEnums {

  type Status = Status.Value
  type Strategy = Strategy.Value
  object Status extends Enumeration {
    val Unverified = Value("unverified")
    val Verified = Value("verified")
    val Failed = Value("failed")
    val Expired = Value("expired")
    val Transferable = Value("transferable")
  }

  object Strategy extends Enumeration {
    val Saml = Value("saml")
  }

}
