/**
 * Clerk Backend API
 * The Clerk REST Backend API, meant to be accessed by backend servers. Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.davisuga.clerk4s.model


case class SAMLAccount(
  id: String,
  /* String representing the object's type. Objects of the same type share the same value.  */
  `object`: SAMLAccountEnums.`Object`,
  provider: String,
  active: Boolean,
  emailAddress: String,
  firstName: Option[String] = None,
  lastName: Option[String] = None,
  providerUserId: Option[String] = None,
  verification: SAMLAccountVerification
)

object SAMLAccountEnums {

  type `Object` = `Object`.Value
  object `Object` extends Enumeration {
    val SamlAccount = Value("saml_account")
  }

}
