/**
 * Clerk Backend API
 * The Clerk REST Backend API, meant to be accessed by backend servers. Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.davisuga.clerk4s.model


case class Session(
  /* String representing the object's type. Objects of the same type share the same value.  */
  `object`: SessionEnums.`Object`,
  id: String,
  userId: String,
  clientId: String,
  actor: Option[Any] = None,
  status: SessionEnums.Status,
  lastActiveOrganizationId: Option[String] = None,
  lastActiveAt: Int,
  expireAt: Int,
  abandonAt: Int,
  /* Unix timestamp of last update.  */
  updatedAt: Long,
  /* Unix timestamp of creation.  */
  createdAt: Long
)

object SessionEnums {

  type `Object` = `Object`.Value
  type Status = Status.Value
  object `Object` extends Enumeration {
    val Session = Value("session")
  }

  object Status extends Enumeration {
    val Active = Value("active")
    val Revoked = Value("revoked")
    val Ended = Value("ended")
    val Expired = Value("expired")
    val Removed = Value("removed")
    val Abandoned = Value("abandoned")
  }

}
