/**
 * Clerk Backend API
 * The Clerk REST Backend API, meant to be accessed by backend servers. Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.davisuga.clerk4s.model


case class SignUp(
  `object`: SignUpEnums.`Object`,
  id: String,
  status: SignUpEnums.Status,
  requiredFields: Option[Seq[String]] = None,
  optionalFields: Option[Seq[String]] = None,
  missingFields: Option[Seq[String]] = None,
  unverifiedFields: Option[Seq[String]] = None,
  verifications: Option[Any] = None,
  username: Option[String] = None,
  emailAddress: Option[String] = None,
  phoneNumber: Option[String] = None,
  web3Wallet: Option[String] = None,
  passwordEnabled: Boolean,
  firstName: Option[String] = None,
  lastName: Option[String] = None,
  unsafeMetadata: Option[Any] = None,
  publicMetadata: Option[Any] = None,
  customAction: Boolean,
  externalId: Option[String] = None,
  createdSessionId: Option[String] = None,
  createdUserId: Option[String] = None,
  abandonAt: Int,
  externalAccount: Option[Any] = None
)

object SignUpEnums {

  type `Object` = `Object`.Value
  type Status = Status.Value
  object `Object` extends Enumeration {
    val SignUpAttempt = Value("sign_up_attempt")
  }

  object Status extends Enumeration {
    val MissingRequirements = Value("missing_requirements")
    val Complete = Value("complete")
    val Abandoned = Value("abandoned")
  }

}
