/**
 * Clerk Backend API
 * The Clerk REST Backend API, meant to be accessed by backend servers. Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.davisuga.clerk4s.model


case class SMSMessage(
  `object`: SMSMessageEnums.`Object`,
  id: String,
  slug: Option[String] = None,
  fromPhoneNumber: String,
  toPhoneNumber: String,
  phoneNumberId: String,
  userId: Option[String] = None,
  message: String,
  status: String,
  data: Option[Any] = None,
  deliveredByClerk: Boolean
)

object SMSMessageEnums {

  type `Object` = `Object`.Value
  object `Object` extends Enumeration {
    val SmsMessage = Value("sms_message")
  }

}
