/**
 * Clerk Backend API
 * The Clerk REST Backend API, meant to be accessed by backend servers. Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.davisuga.clerk4s.model


case class Template(
  id: Option[String] = None,
  /* String representing the object's type. Objects of the same type share the same value.  */
  `object`: Option[TemplateEnums.`Object`] = None,
  /* the id of the instance the template belongs to */
  instanceId: Option[String] = None,
  /* whether this is a system (default) or user overridden) template */
  resourceType: Option[String] = None,
  /* whether this is an email or SMS template */
  templateType: Option[String] = None,
  /* user-friendly name of the template */
  name: Option[String] = None,
  /* machine-friendly name of the template */
  slug: Option[String] = None,
  /* position with the listing of templates */
  position: Option[Int] = None,
  /* whether this template can be reverted to the corresponding system default */
  canRevert: Option[Boolean] = None,
  /* whether this template can be deleted */
  canDelete: Option[Boolean] = None,
  /* email subject */
  subject: Option[String] = None,
  /* the editor markup used to generate the body of the template */
  markup: Option[String] = None,
  /* the template body before variable interpolation */
  body: Option[String] = None,
  /* list of variables that are available for use in the template body */
  availableVariables: Option[Seq[String]] = None,
  /* list of variables that must be contained in the template body */
  requiredVariables: Option[Seq[String]] = None,
  fromEmailName: Option[String] = None,
  deliveredByClerk: Option[Boolean] = None,
  /* Unix timestamp of last update.  */
  updatedAt: Option[Long] = None,
  /* Unix timestamp of creation.  */
  createdAt: Option[Long] = None
)

object TemplateEnums {

  type `Object` = `Object`.Value
  object `Object` extends Enumeration {
    val Template = Value("template")
  }

}
