/**
 * Clerk Backend API
 * The Clerk REST Backend API, meant to be accessed by backend servers. Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.davisuga.clerk4s.model


case class TotalCount(
  /* String representing the object's type. Objects of the same type share the same value.  */
  `object`: TotalCountEnums.`Object`,
  totalCount: Long
)

object TotalCountEnums {

  type `Object` = `Object`.Value
  object `Object` extends Enumeration {
    val TotalCount = Value("total_count")
  }

}
