/**
 * Clerk Backend API
 * The Clerk REST Backend API, meant to be accessed by backend servers. Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.davisuga.clerk4s.model


case class UpdateInstanceRequest(
  /* Toggles test mode for this instance, allowing the use of test email addresses and phone numbers. Defaults to true for development instances. */
  testMode: Option[Boolean] = None,
  /* Whether the instance should be using the HIBP service to check passwords for breaches */
  hibp: Option[Boolean] = None,
  /* The \"enhanced_email_deliverability\" feature will send emails from \"verifications@clerk.dev\" instead of your domain. This can be helpful if you do not have a high domain reputation. */
  enhancedEmailDeliverability: Option[Boolean] = None,
  supportEmail: Option[String] = None,
  clerkJsVersion: Option[String] = None,
  developmentOrigin: Option[String] = None,
  /* For browser-like stacks such as browser extensions, Electron, or Capacitor.js the instance allowed origins need to be updated with the request origin value. For Chrome extensions popup, background, or service worker pages the origin is chrome-extension://extension_uiid. For Electron apps the default origin is http://localhost:3000. For Capacitor, the origin is capacitor://localhost. */
  allowedOrigins: Option[Seq[String]] = None,
  /* Whether the instance should operate in cookieless development mode (i.e. without third-party cookies). Deprecated: Please use `url_based_session_syncing` instead. */
  cookielessDev: Option[Boolean] = None,
  /* Whether the instance should use URL-based session syncing in development mode (i.e. without third-party cookies). */
  urlBasedSessionSyncing: Option[Boolean] = None
)

