/**
 * Clerk Backend API
 * The Clerk REST Backend API, meant to be accessed by backend servers. Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.davisuga.clerk4s.model


case class UpdateInstanceAuthConfig200Response(
  /* String representing the object's type. Objects of the same type share the same value. */
  `object`: Option[UpdateInstanceAuthConfig200ResponseEnums.`Object`] = None,
  id: Option[String] = None,
  restrictedToAllowlist: Option[Boolean] = None,
  fromEmailAddress: Option[String] = None,
  progressiveSignUp: Option[Boolean] = None,
  enhancedEmailDeliverability: Option[Boolean] = None
)

object UpdateInstanceAuthConfig200ResponseEnums {

  type `Object` = `Object`.Value
  object `Object` extends Enumeration {
    val InstanceSettings = Value("instance_settings")
  }

}
