/**
 * Clerk Backend API
 * The Clerk REST Backend API, meant to be accessed by backend servers. Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.davisuga.clerk4s.model


case class UpdateInstanceAuthConfigRequest(
  /* Whether sign up is restricted to email addresses, phone numbers and usernames that are on the allowlist. */
  restrictedToAllowlist: Option[Boolean] = None,
  /* The local part of the email address from which authentication-related emails (e.g. OTP code, magic links) will be sent. Only alphanumeric values are allowed. Note that this value should contain only the local part of the address (e.g. `foo` for `foo@example.com`). */
  fromEmailAddress: Option[String] = None,
  /* Enable the Progressive Sign Up algorithm. Refer to the [docs](https://clerk.com/docs/upgrade-guides/progressive-sign-up) for more info. */
  progressiveSignUp: Option[Boolean] = None,
  /* The name of the JWT Template used to augment your session tokens. To disable this, pass an empty string. */
  sessionTokenTemplate: Option[String] = None,
  /* The \"enhanced_email_deliverability\" feature will send emails from \"verifications@clerk.dev\" instead of your domain. This can be helpful if you do not have a high domain reputation. */
  enhancedEmailDeliverability: Option[Boolean] = None,
  /* Toggles test mode for this instance, allowing the use of test email addresses and phone numbers. Defaults to true for development instances. */
  testMode: Option[Boolean] = None
)

