/**
 * Clerk Backend API
 * The Clerk REST Backend API, meant to be accessed by backend servers. Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.davisuga.clerk4s.model


case class UpdateOrganizationRequest(
  /* Metadata saved on the organization, that is visible to both your frontend and backend. */
  publicMetadata: Option[Any] = None,
  /* Metadata saved on the organization that is only visible to your backend. */
  privateMetadata: Option[Any] = None,
  /* The new name of the organization */
  name: Option[String] = None,
  /* The new slug of the organization, which needs to be unique in the instance */
  slug: Option[String] = None,
  /* The maximum number of memberships allowed for this organization */
  maxAllowedMemberships: Option[Int] = None,
  /* If true, an admin can delete this organization with the Frontend API. */
  adminDeleteEnabled: Option[Boolean] = None
)

