/**
 * Clerk Backend API
 * The Clerk REST Backend API, meant to be accessed by backend servers. Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.davisuga.clerk4s.model


case class UpdateUserRequest(
  /* The ID of the user as used in your external systems or your previous authentication solution. Must be unique across your instance. */
  externalId: Option[String] = None,
  /* The first name to assign to the user */
  firstName: Option[String] = None,
  /* The last name to assign to the user */
  lastName: Option[String] = None,
  /* The ID of the email address to set as primary. It must be verified, and present on the current user. */
  primaryEmailAddressId: Option[String] = None,
  /* The ID of the phone number to set as primary. It must be verified, and present on the current user. */
  primaryPhoneNumberId: Option[String] = None,
  /* The ID of the web3 wallets to set as primary. It must be verified, and present on the current user. */
  primaryWeb3WalletId: Option[String] = None,
  /* The username to give to the user. It must be unique across your instance. */
  username: Option[String] = None,
  /* The ID of the image to set as the user's profile image */
  profileImageId: Option[String] = None,
  /* The plaintext password to give the user. Must be at least 8 characters long, and can not be in any list of hacked passwords. */
  password: Option[String] = None,
  /* Set it to `true` if you're updating the user's password and want to skip any password policy settings check. This parameter can only be used when providing a `password`. */
  skipPasswordChecks: Option[Boolean] = None,
  /* Set to `true` to sign out the user from all their active sessions once their password is updated. This parameter can only be used when providing a `password`. */
  signOutOfOtherSessions: Option[Boolean] = None,
  /* In case TOTP is configured on the instance, you can provide the secret to enable it on the specific user without the need to reset it. Please note that currently the supported options are: * Period: 30 seconds * Code length: 6 digits * Algorithm: SHA1 */
  totpSecret: Option[String] = None,
  /* If Backup Codes are configured on the instance, you can provide them to enable it on the specific user without the need to reset them. You must provide the backup codes in plain format or the corresponding bcrypt digest. */
  backupCodes: Option[Seq[String]] = None,
  /* Metadata saved on the user, that is visible to both your Frontend and Backend APIs */
  publicMetadata: Option[Any] = None,
  /* Metadata saved on the user, that is only visible to your Backend API */
  privateMetadata: Option[Any] = None,
  /* Metadata saved on the user, that can be updated from both the Frontend and Backend APIs. Note: Since this data can be modified from the frontend, it is not guaranteed to be safe. */
  unsafeMetadata: Option[Any] = None,
  /* If true, the user can delete themselves with the Frontend API. */
  deleteSelfEnabled: Option[Boolean] = None,
  /* If true, the user can create organizations with the Frontend API. */
  createOrganizationEnabled: Option[Boolean] = None,
  /* A custom date/time denoting _when_ the user signed up to the application, specified in RFC3339 format (e.g. `2012-10-20T07:15:20.902Z`). */
  createdAt: Option[String] = None
)

