/**
 * Clerk Backend API
 * The Clerk REST Backend API, meant to be accessed by backend servers. Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.davisuga.clerk4s.model


case class VerifyTOTP200Response(
  verified: Option[Boolean] = None,
  codeType: Option[VerifyTOTP200ResponseEnums.CodeType] = None
)

object VerifyTOTP200ResponseEnums {

  type CodeType = CodeType.Value
  object CodeType extends Enumeration {
    val Totp = Value("totp")
    val BackupCode = Value("backup_code")
  }

}
