/**
 * Clerk Backend API
 * The Clerk REST Backend API, meant to be accessed by backend servers. Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.davisuga.clerk4s.model


case class Web3Signature(
  status: Web3SignatureEnums.Status,
  strategy: Web3SignatureEnums.Strategy,
  nonce: Web3SignatureEnums.Nonce,
  attempts: Option[Int] = None,
  expireAt: Option[Int] = None
)

object Web3SignatureEnums {

  type Status = Status.Value
  type Strategy = Strategy.Value
  type Nonce = Nonce.Value
  object Status extends Enumeration {
    val Verified = Value("verified")
  }

  object Strategy extends Enumeration {
    val Web3MetamaskSignature = Value("web3_metamask_signature")
  }

  object Nonce extends Enumeration {
    val Nonce = Value("nonce")
  }

}
