/**
 * Clerk Backend API
 * The Clerk REST Backend API, meant to be accessed by backend servers. Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.davisuga.clerk4s.model


case class Web3Wallet(
  id: Option[String] = None,
  /* String representing the object's type. Objects of the same type share the same value.  */
  `object`: Web3WalletEnums.`Object`,
  web3Wallet: String,
  verification: Web3WalletVerification
)

object Web3WalletEnums {

  type `Object` = `Object`.Value
  object `Object` extends Enumeration {
    val Web3Wallet = Value("web3_wallet")
  }

}
